apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
 labels:
   coo: coo-monitoring-stack
 name: coo-monitoring-stack
spec:
 alertmanagerConfig:
   disabled: true
 prometheusConfig:
   replicas: 1
 retention: 2d
 resourceSelector:
   matchLabels:
     monitoredby: coo-monitoring-stack