kind: TempoMonolithic
apiVersion: tempo.grafana.com/v1alpha1
metadata:
  name: tempo1
  namespace: tempo-monolithic
spec:
  jaegerui:
    enabled: true
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
    route:
      enabled: true
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
  storage:
    traces:
      backend: memory
