apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: my-app
      namespace: node-prom
      labels:
        project: my-app
        version: 1.0.0
        provider: nodeshift
        app: my-app
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: my-app
        app.kubernetes.io/instance: my-app
        app.openshift.io/runtime: nodejs
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: my-app
        project: my-app
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - my-app
            from:
              kind: ImageStreamTag
              namespace: node-prom
              name: 'my-app:latest'
      template:
        metadata:
          labels:
            project: my-app
            version: 1.0.0
            provider: nodeshift
            app: my-app
        spec:
          containers:
            - image: my-app
              name: my-app
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env: []
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: my-app
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: my-app
      namespace: node-prom
      labels:
        project: my-app
        version: 1.0.0
        provider: nodeshift
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: my-app
        app.kubernetes.io/instance: my-app
        app.openshift.io/runtime: nodejs
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      to:
        kind: Service
        name: my-app
      port:
        targetPort: 8080
    metadata:
      name: my-app
      labels:
        project: my-app
        version: 1.0.0
        provider: nodeshift
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: my-app
        app.kubernetes.io/instance: my-app
        app.openshift.io/runtime: nodejs
